version: 3

tasks:
    generate:
        cmds:
            - protoc -I proto proto/sso/auth.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
            - protoc -I proto proto/sso/directory.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
